# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.200.15.254:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.200.15.254"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ms1"
    ipAddress: "10.200.15.51"
    installDiskSelector:
      serial: "1925E20E2038"
    userVolumes:
      - name: local-hostpath
        provisioning:
          minSize: 1TB
          grow: true
          diskSelector:
            match: disk.model == "WD_BLACK SN770 2TB"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:38"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:39"
        ignore: true
        #bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:cf:*"
              driver: i40e
          xmitHashPolicy: layer3+4
          lacpRate: fast
          miimon: 1000
        dhcp: false
        addresses:
          - "10.200.15.51/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
        vip:
          ip: "10.200.15.254"
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "ms2"
    ipAddress: "10.200.15.52"
    installDiskSelector:
      serial: "220628801124"
    userVolumes:
      - name: local-hostpath
        provisioning:
          minSize: 1TB
          grow: true
          diskSelector:
            match: disk.model == "WD_BLACK SN770 2TB"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f1:34"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f1:35"
        ignore: true
        #bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            -  hardwareAddr: "58:47:ca:78:f1:*"
               driver: i40e
          xmitHashPolicy: layer3+4
          lacpRate: fast
          miimon: 1000
        dhcp: false
        addresses:
          - "10.200.15.52/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
        vip:
          ip: "10.200.15.254"
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "ms3"
    ipAddress: "10.200.15.53"
    installDiskSelector:
      serial: "22061X806789"
    userVolumes:
      - name: local-hostpath
        provisioning:
          minSize: 1TB
          grow: true
          diskSelector:
            match: disk.model == "WD_BLACK SN770 2TB"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f8:4c"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f8:4d"
        ignore: true
        #bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            -  hardwareAddr: "58:47:ca:78:f8:*"
               driver: i40e
          xmitHashPolicy: layer3+4
          lacpRate: fast
          miimon: 1000
        dhcp: false
        addresses:
          - "10.200.15.53/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
        vip:
          ip: "10.200.15.254"
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "blade5"
    ipAddress: "10.200.15.35"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800811"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
        #bond0
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "e4:5f:01:ec:16:b4"
        dhcp: false
        addresses:
          - "10.200.15.35/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "blade6"
    ipAddress: "10.200.15.36"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800731"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
        #bond0
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "e4:5f:01:ec:16:a5"
        dhcp: false
        addresses:
          - "10.200.15.36/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "blade7"
    ipAddress: "10.200.15.37"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800801"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
        #bond0
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "e4:5f:01:ec:16:9c"
        dhcp: false
        addresses:
          - "10.200.15.37/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
  - hostname: "blade8"
    ipAddress: "10.200.15.38"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800737"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
        #bond0
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "e4:5f:01:ec:16:5a"
        dhcp: false
        addresses:
          - "10.200.15.38/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.200.15.1"
            metric: 1
        mtu: 1500
    extensionServices:
      - name: nut-client
        configFiles:
          - content: |-
              MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
              SHUTDOWNCMD "/sbin/poweroff"
            mountPath: /usr/local/etc/nut/upsmon.conf
# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-files-nfs.yaml"
  - "@./patches/global/machine-hostdns.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/openebs-local.yaml"

# Controller patches
controlPlane:

  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/gasket-driver    # Google Coral M.2
          - siderolabs/i915             # MS-01 CPU iGraphics
          - siderolabs/intel-ucode      # Intel ucode
          - siderolabs/mei
          - siderolabs/thunderbolt      # Thunderbolt networking

  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/enable-talos-api.yaml"
    - "@./patches/controller/machine-install.yaml"


    # Custom sysfs settings
    - |-
      machine:
        sysfs:
          devices.system.cpu.intel_pstate.hwp_dynamic_boost: 1
          devices.system.cpu.cpu0.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu1.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu2.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu3.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu4.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu5.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu6.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu7.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu8.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu9.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu10.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu11.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu12.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu13.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu14.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu15.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu16.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu17.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu18.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu19.cpufreq.energy_performance_preference: balance_performance

    # Enable thunderbolt + net
    - |-
      machine:
        kernel:
          modules:
            - name: nbd
            - name: thunderbolt
            - name: thunderbolt_net

    # Various udev rules
    - |-
      machine:
        udev:
          rules:
            # Thunderbolt
            - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
            # Coral Edge TPU
            - SUBSYSTEM=="apex", KERNEL=="apex*", GROUP="44", MODE="0660"
